services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./migration/define_db.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      - POSTGRES_USER=gym
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=academia
    ports: 
      - "5432:5432"
      
volumes:
  postgres-db-volume:
    
